web:
  build: .
  links:
    - db
  environment:
    - DB_HOST=db
    - PORT=8000
  container_name: hello-nextjs
  ports:
    - '8888:8000'
db:
  container_name: mongodb-nextjs
  image: mongo
  ports:
    - '27017:27017'